#!/usr/bin/env python3
"""Golden vectors for the SquachMesh message frame.

Builds complete message frames -- key stretching, nonce, associated data,
AES-128-CCM and tag, and for a typed message the six-bit text packing -- with
Python's `cryptography` package, and writes the exact bytes to
include/meshmsg_vectors.h.

This is a SECOND IMPLEMENTATION of the frame format documented in
include/meshmsg.h, written from that description rather than by calling the
firmware -- and that is the whole point. The device rebuilds these frames with
mbedtls at every boot (MeshCrypto::selfTest) and refuses to send or read a
message if a single byte differs. The host tests check the headers and nonce.
Two implementations that must agree about a format neither owns is a test; one
implementation checked against itself is not.

Run by hand; CI has no `cryptography`, and the output is checked in:

    python test/gen_meshmsg_vectors.py

The inputs are arbitrary. Change them only if you mean to change the golden
frames, and rebuild the firmware afterwards.
"""
import os

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESCCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "include", "meshmsg_vectors.h"))

SALT = b"SquachWatch/msg/v1"
PHRASE = "GIBSON MOTHMAN PHREAK NESSIE ZEROCOOL"
ITERS = 2            # the device uses thousands; the self-test proves the wiring
MAC = bytes([0x24, 0x0A, 0xC4, 0x12, 0x34, 0x56])
COUNTER = 0x010203   # three bytes in version 2
CANNED = 7
# Two parts: the golden frame is the SECOND, so the part index, the padding
# and the counter offset are all exercised at once.
TEXT = "MEET AT THE CAR IN 5 MIN, OK?"
TEXT_PART = 1

MAGIC = b"ST"
VERSION = 2
KIND_CANNED = 1
KIND_TEXT = 2
CHARSET = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,?!'-"
END = 63
PART_CHARS = 16

key = PBKDF2HMAC(algorithm=hashes.SHA256(), length=16, salt=SALT,
                 iterations=ITERS).derive(PHRASE.encode("ascii"))
ccm = AESCCM(key, tag_length=8)


def header(kind, ctr):
    return MAGIC + bytes([(VERSION << 4) | kind]) + ctr.to_bytes(3, "little")


def nonce_for(ctr):
    return MAC + ctr.to_bytes(3, "little") + bytes(4)


# ---- canned ----
h = header(KIND_CANNED, COUNTER)
nonce = nonce_for(COUNTER)
# AESCCM returns ciphertext followed by the tag, which is exactly the frame's
# order after the header.
frame = h + ccm.encrypt(nonce, bytes([CANNED]), h)
assert len(nonce) == 13 and len(frame) == 15, (len(nonce), len(frame))

# ---- typed ----
total = (len(TEXT) + PART_CHARS - 1) // PART_CHARS
seg = TEXT[TEXT_PART * PART_CHARS:(TEXT_PART + 1) * PART_CHARS]
codes = [CHARSET.index(c) for c in seg] + [END] * (PART_CHARS - len(seg))
bits = "".join(format(c, "06b") for c in codes)             # 96 bits, MSB first
packed = int(bits, 2).to_bytes(12, "big")
text_ctr = COUNTER + TEXT_PART          # consecutive counters, one per part
th = header(KIND_TEXT, text_ctr)
text_frame = th + ccm.encrypt(nonce_for(text_ctr), bytes([(TEXT_PART << 4) | total]) + packed, th)
assert total == 2 and len(text_frame) == 27, (total, len(text_frame))


def arr(b):
    return ", ".join("0x%02X" % x for x in b)


lines = [
    "// GENERATED by test/gen_meshmsg_vectors.py -- do not edit by hand.",
    "//",
    "// SquachMesh message frames built by Python's `cryptography` -- an",
    "// implementation that shares no code with the firmware's. MeshCrypto::selfTest",
    "// rebuilds them with mbedtls at every boot and demands the same bytes; the host",
    "// tests check their headers and nonce. The generator documents the inputs.",
    "#pragma once",
    "#include <stdint.h>",
    "",
    "namespace MeshMsgVec {",
    'constexpr char     SALT[]    = "%s";' % SALT.decode("ascii"),
    'constexpr char     PHRASE[]  = "%s";' % PHRASE,
    "constexpr uint32_t ITERS     = %d;" % ITERS,
    "constexpr uint8_t  KEY[16]   = { %s };" % arr(key),
    "constexpr uint8_t  MAC[6]    = { %s };" % arr(MAC),
    "constexpr uint32_t COUNTER   = 0x%06X;" % COUNTER,
    "constexpr uint8_t  CANNED    = %d;" % CANNED,
    "constexpr uint8_t  NONCE[13] = { %s };" % arr(nonce),
    "constexpr uint8_t  FRAME[15] = { %s };" % arr(frame),
    "// Part TEXT_PART of TEXT, at counter COUNTER + TEXT_PART.",
    'constexpr char     TEXT[]    = "%s";' % TEXT,
    "constexpr uint8_t  TEXT_PART = %d;" % TEXT_PART,
    "constexpr uint8_t  TEXT_FRAME[27] = { %s };" % arr(text_frame),
    "} // namespace MeshMsgVec",
    "",
]
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(lines))

print("key        ", key.hex())
print("nonce      ", nonce.hex())
print("frame      ", frame.hex())
print("text frame ", text_frame.hex())
print("->", OUT)
