#!/usr/bin/env python3
"""Golden vectors for the SquachMesh message frame.

Builds one complete message frame -- key stretching, nonce, associated data,
AES-128-CCM and tag -- with Python's `cryptography` package, and writes the
exact bytes to include/meshmsg_vectors.h.

This is a SECOND IMPLEMENTATION of the frame format documented in
include/meshmsg.h, written from that description rather than by calling the
firmware -- and that is the whole point. The device rebuilds this frame with
mbedtls at every boot (MeshCrypto::selfTest) and refuses to send or read a
message if a single byte differs. The host tests check its header and nonce.
Two implementations that must agree about a format neither owns is a test; one
implementation checked against itself is not.

Run by hand; CI has no `cryptography`, and the output is checked in:

    python test/gen_meshmsg_vectors.py

The inputs are arbitrary. Change them only if you mean to change the golden
frame, and rebuild the firmware afterwards.
"""
import os

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESCCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "include", "meshmsg_vectors.h"))

SALT = b"SquachWatch/msg/v1"
PHRASE = "GIBSON MOTHMAN PHREAK NESSIE ZEROCOOL"
ITERS = 2            # the device uses thousands; the self-test proves the wiring
MAC = bytes([0x24, 0x0A, 0xC4, 0x12, 0x34, 0x56])
COUNTER = 0x01020304
CANNED = 7

MAGIC = b"SQMT"
VERSION = 1
KIND_CANNED = 1

key = PBKDF2HMAC(algorithm=hashes.SHA256(), length=16, salt=SALT,
                 iterations=ITERS).derive(PHRASE.encode("ascii"))
header = MAGIC + bytes([VERSION, KIND_CANNED]) + COUNTER.to_bytes(4, "little")
nonce = MAC + COUNTER.to_bytes(4, "little") + bytes(3)
# AESCCM returns ciphertext followed by the tag, which is exactly the frame's
# order after the header.
frame = header + AESCCM(key, tag_length=8).encrypt(nonce, bytes([CANNED]), header)
assert len(nonce) == 13 and len(frame) == 19, (len(nonce), len(frame))


def arr(b):
    return ", ".join("0x%02X" % x for x in b)


lines = [
    "// GENERATED by test/gen_meshmsg_vectors.py -- do not edit by hand.",
    "//",
    "// One SquachMesh message frame, built by Python's `cryptography` -- an",
    "// implementation that shares no code with the firmware's. MeshCrypto::selfTest",
    "// rebuilds it with mbedtls at every boot and demands the same bytes; the host",
    "// tests check its header and nonce. The generator documents the inputs.",
    "#pragma once",
    "#include <stdint.h>",
    "",
    "namespace MeshMsgVec {",
    'constexpr char     SALT[]    = "%s";' % SALT.decode("ascii"),
    'constexpr char     PHRASE[]  = "%s";' % PHRASE,
    "constexpr uint32_t ITERS     = %d;" % ITERS,
    "constexpr uint8_t  KEY[16]   = { %s };" % arr(key),
    "constexpr uint8_t  MAC[6]    = { %s };" % arr(MAC),
    "constexpr uint32_t COUNTER   = 0x%08X;" % COUNTER,
    "constexpr uint8_t  CANNED    = %d;" % CANNED,
    "constexpr uint8_t  NONCE[13] = { %s };" % arr(nonce),
    "constexpr uint8_t  FRAME[19] = { %s };" % arr(frame),
    "} // namespace MeshMsgVec",
    "",
]
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(lines))

print("key   ", key.hex())
print("nonce ", nonce.hex())
print("frame ", frame.hex())
print("->", OUT)
