// GENERATED by test/gen_meshmsg_vectors.py -- do not edit by hand.
//
// One SquachMesh message frame, built by Python's `cryptography` -- an
// implementation that shares no code with the firmware's. MeshCrypto::selfTest
// rebuilds it with mbedtls at every boot and demands the same bytes; the host
// tests check its header and nonce. The generator documents the inputs.
#pragma once
#include <stdint.h>

namespace MeshMsgVec {
constexpr char     SALT[]    = "SquachWatch/msg/v1";
constexpr char     PHRASE[]  = "GIBSON MOTHMAN PHREAK NESSIE ZEROCOOL";
constexpr uint32_t ITERS     = 2;
constexpr uint8_t  KEY[16]   = { 0x8D, 0xAE, 0x79, 0x72, 0x37, 0xCF, 0xC2, 0x16, 0xBC, 0x46, 0x16, 0x38, 0x0D, 0xE9, 0xFF, 0x7F };
constexpr uint8_t  MAC[6]    = { 0x24, 0x0A, 0xC4, 0x12, 0x34, 0x56 };
constexpr uint32_t COUNTER   = 0x01020304;
constexpr uint8_t  CANNED    = 7;
constexpr uint8_t  NONCE[13] = { 0x24, 0x0A, 0xC4, 0x12, 0x34, 0x56, 0x04, 0x03, 0x02, 0x01, 0x00, 0x00, 0x00 };
constexpr uint8_t  FRAME[19] = { 0x53, 0x51, 0x4D, 0x54, 0x01, 0x01, 0x04, 0x03, 0x02, 0x01, 0xB7, 0xF7, 0xD5, 0xCF, 0xE3, 0x03, 0xD5, 0x37, 0x7D };
} // namespace MeshMsgVec
