#!/usr/bin/env python3
"""Turn cty.dat into include/lora_dxcc_table.h -- callsign prefix to DXCC entity.

    curl -O https://www.country-files.com/cty/cty.dat
    python3 tools/gen_dxcc.py cty.dat > include/lora_dxcc_table.h

cty.dat is Jim Reisert AD1C's country file, MIT licensed
(https://www.country-files.com/copyright/), and is updated roughly
fortnightly, so this is a generator and not a hand-maintained table.

WHAT IS KEPT, AND WHY IT IS NOT THE WHOLE FILE. Measured over the file
downloaded 2026-09-26 (106,119 bytes, 346 entities): it holds 4,798 distinct
plain prefixes plus 2,722 `=CALL` exact-callsign overrides.

  - The exact-callsign overrides are dropped. They name individual operators
    who are somewhere other than their prefix says, which is a fact about a
    person rather than about a prefix, and 2,722 of them cost more flash than
    the whole rest of the table.
  - Prefixes of four and five characters are dropped UNLESS they name a
    different entity from the answer their first three characters give. Of
    3,331 such prefixes, 500 change the entity (BV9P Pratas against BV
    Taiwan, CE0Z Juan Fernandez against CE Chile) and 2,831 only refine the
    CQ or ITU zone inside one country -- US and Russian call areas, mostly.
    Keeping the 500 makes the ENTITY answer identical to the full file's;
    dropping the 2,831 is why this table is 21 kB and not 43 kB.
  - CQ and ITU zones are therefore NOT emitted at all. With the call-area
    rows gone, the only zone left to report would be the entity's default,
    which is wrong for every country that spans more than one zone -- the
    United States spans CQ 3 to 5. A number that is right for Germany and
    wrong for America is worse than no number, so the device shows the
    entity and the continent and says nothing about zones.

The lookup is longest-prefix-first, so a row is reachable only if every
shorter prefix of it misses: see Lora::Ident::dxcc().
"""
import re
import sys
import collections


def parse(path):
    raw = open(path, encoding='latin-1').read()
    ents = []          # (name, continent)
    pfx = {}           # prefix -> entity index
    for rec in (r for r in raw.split(';') if r.strip()):
        f = rec.split(':')
        if len(f) < 9:
            print('skipped a record with %d fields' % len(f), file=sys.stderr)
            continue
        ents.append((f[0].strip(), f[3].strip()))
        for tok in f[8].replace('\n', '').replace(' ', '').split(','):
            if not tok or tok.startswith('='):
                continue
            # Per-prefix overrides: (cq) [itu] <lat/lon> {continent} ~tz~.
            # Stripped -- none of them survives into the table (see above).
            t = re.sub(r'\(\d+\)|\[\d+\]|<[^>]*>|\{[^}]*\}|~[^~]*~', '', tok).lstrip('*')
            if t:
                pfx[t] = len(ents) - 1
    return ents, pfx


def longest(pfx, call, maxlen):
    for n in range(min(len(call), maxlen), 0, -1):
        if call[:n] in pfx:
            return pfx[call[:n]]
    return None


def main():
    if len(sys.argv) != 2:
        sys.exit('usage: gen_dxcc.py cty.dat > include/lora_dxcc_table.h')
    ents, pfx = parse(sys.argv[1])
    short = {k: v for k, v in pfx.items() if len(k) <= 3}
    keep = dict(short)
    changed = 0
    for k, v in pfx.items():
        if len(k) <= 3:
            continue
        if longest(short, k, 3) != v:
            keep[k] = v
            changed += 1

    used = sorted(set(keep.values()))
    remap = {e: i for i, e in enumerate(used)}
    conts = sorted(set(ents[e][1] for e in used))

    rows = sorted(keep.items())
    bytes_pfx = sum(len(k) + 1 for k, _ in rows)
    bytes_tbl = len(rows) * 8 + sum(len(ents[e][0]) + 1 for e in used) + len(used) * 8

    out = sys.stdout.write
    out('// Generated by tools/gen_dxcc.py from cty.dat -- do not edit.\n')
    out('//\n')
    out('// cty.dat (c) Jim Reisert AD1C, MIT licence:\n')
    out('// https://www.country-files.com/copyright/\n')
    out('//\n')
    out('// %d entities, %d prefixes: %d of 1-3 characters, plus %d longer ones\n'
        % (len(used), len(rows), len(short), changed))
    out('// that name a different entity from their own first three. About %.1f kB\n'
        % (bytes_tbl / 1024.0))
    out('// of flash. See the generator for what was left out and why.\n')
    out('#pragma once\n#include <stdint.h>\n\n')
    out('namespace Lora {\nnamespace Ident {\n\n')

    out('// Continents, as cty.dat spells them.\n')
    out('static const char* const DXCC_CONT[] = { %s };\n\n'
        % ', '.join('"%s"' % c for c in conts))

    out('struct DxccEntity { const char* name; uint8_t cont; };\n')
    out('static const DxccEntity DXCC_ENT[] = {\n')
    for e in used:
        name, cont = ents[e]
        out('    { "%s", %d },\n' % (name.replace('"', '\\"'), conts.index(cont)))
    out('};\n\n')

    out('// Sorted by prefix, so the lookup binary-searches one length at a time.\n')
    out('struct DxccPrefix { char p[%d]; uint16_t ent; };\n' % (max(len(k) for k in keep) + 1))
    out('static const DxccPrefix DXCC_PFX[] = {\n')
    for i in range(0, len(rows), 4):
        out('    ' + ' '.join('{ "%s", %d },' % (k, remap[v]) for k, v in rows[i:i + 4]) + '\n')
    out('};\n\n')
    out('static const uint8_t DXCC_MAX_PFX = %d;\n\n' % max(len(k) for k in keep))
    out('}\n}\n')

    lens = collections.Counter(len(k) for k in keep)
    print('%d entities, %d prefixes %s, ~%d bytes of prefix text'
          % (len(used), len(rows), dict(sorted(lens.items())), bytes_pfx), file=sys.stderr)


if __name__ == '__main__':
    main()
