#!/usr/bin/env python3
"""Turn TTN's prefix-assignment table into include/lora_netid_table.h.

    curl -o prefixes.html https://www.thethingsnetwork.org/docs/lorawan/prefix-assignments/
    python3 tools/gen_netid.py prefixes.html tools/netid_extra.csv > include/lora_netid_table.h

The authoritative registry is the LoRa Alliance's NetID allocation R111, which
is a PDF (cited in docs/LORA.md's sources). The TTN docs page publishes the
same allocation as an HTML table, one row per NetID with its DevAddr prefix in
CIDR form, and that is machine-readable.

The page also cross-checks src/lora_lorawan.cpp's bit layout without opening
the spec: parsed 2026-09-26 it gives 204 rows whose prefix widths are /7, /15,
/22 and /25 -- exactly 1+6, 4+11, 7+15 and 8+17, the type prefix length plus
NWKID_BITS[type] for types 0, 3, 6 and 7. If a future run of this script sees
a width that is not one of those, the table in lookupDevAddr() is wrong or the
registry has grown a new type, and either way it wants reading before the
generated header is trusted.

Rows marked unassigned or RESERVED are dropped: a DevAddr in one of those
ranges has no operator to name, and saying "unassigned" is what a missing row
already says.

THE PAGE IS NOT THE WHOLE REGISTRY, which is why there is a second input.
It enumerates the 64 type-0 NetIDs and then only a sample of the higher types
-- type 6 alone has 32,768 possible values. Ten of the rows that the
hand-written table in src/lora_lorawan.cpp carried before this generator
existed are therefore not on the page: nine are absent from it entirely and
one, 000006, is listed as unassigned where the hand table names an operator.
Those ten live in tools/netid_extra.csv and are merged in, because dropping a
named operator in favour of a page that does not cover its type would be a
regression dressed up as an update. See that file for their provenance.
"""
import html
import re
import sys

NWKID_BITS = (6, 6, 9, 11, 12, 13, 15, 17)


def rows(page):
    for tr in re.findall(r'<tr>(.*?)</tr>', page, re.S):
        # html.unescape, because the operator column really does contain
        # "&amp;": Alpha-Omega Technology GmbH &amp; Co. KG.
        cells = [html.unescape(re.sub(r'<[^>]+>', '', c)).strip()
                 for c in re.findall(r'<t[dh][^>]*>(.*?)</t[dh]>', tr, re.S)]
        if len(cells) >= 4 and re.fullmatch(r'[0-9A-Fa-f]{6}', cells[0]):
            yield cells


def extras(path):
    """netid,operator rows the page does not cover. Comments start with #."""
    out = []
    for line in open(path, encoding='utf-8'):
        line = line.split('#')[0].strip()
        if not line:
            continue
        netid, op = line.split(',', 1)
        out.append((int(netid, 16), op.strip()))
    return out


def main():
    if len(sys.argv) not in (2, 3):
        sys.exit('usage: gen_netid.py prefix-assignments.html [extra.csv] > include/lora_netid_table.h')
    page = open(sys.argv[1], encoding='utf-8').read()
    seen, out_rows, widths, dropped = set(), [], {}, 0
    for c in rows(page):
        netid, cidr, op = int(c[0], 16), c[1], ' '.join(c[3].split())
        if not op or op.lower() == 'unassigned' or op.upper() == 'RESERVED':
            dropped += 1
            continue
        width = int(cidr.split('/')[1])
        widths[width] = widths.get(width, 0) + 1
        t = netid >> 21
        if width != t + 1 + NWKID_BITS[t]:
            sys.exit('NetID %06X: prefix /%d does not match type %d (%d + %d). '
                     'Read the registry before trusting this table.'
                     % (netid, width, t, t + 1, NWKID_BITS[t]))
        if netid in seen:
            continue
        seen.add(netid)
        out_rows.append((netid, op, False))

    extra = extras(sys.argv[2]) if len(sys.argv) == 3 else []
    for netid, op in extra:
        if netid in seen:
            sys.exit('NetID %06X is in both inputs: the page has caught up, so drop '
                     'the row from the extras file rather than shipping it twice.' % netid)
        seen.add(netid)
        out_rows.append((netid, op, True))

    w = sys.stdout.write
    w('// Generated by tools/gen_netid.py -- do not edit.\n')
    w('//\n')
    w('// LoRaWAN NetID to operator, from TTN\'s published prefix-assignment table\n')
    w('// (https://www.thethingsnetwork.org/docs/lorawan/prefix-assignments/), which\n')
    w('// republishes the LoRa Alliance NetID allocation R111, plus %d rows from\n' % len(extra))
    w('// tools/netid_extra.csv that the page does not cover (marked +). %d rows in all;\n' % len(out_rows))
    w('// %d unassigned or reserved rows are not here, because a missing row says the\n' % dropped)
    w('// same thing. Prefix widths seen: %s.\n'
      % ', '.join('/%d x %d' % (k, v) for k, v in sorted(widths.items())))
    w('#pragma once\n#include <stdint.h>\n\n')
    w('namespace LoRaWAN {\n\n')
    w('struct NetEntry { uint32_t netId; const char* op; };\n')
    w('static const NetEntry REGISTRY[] = {\n')
    last_type = None
    for netid, op, isextra in sorted(out_rows):
        t = netid >> 21
        if t != last_type:
            w('    // Type %d: %d bits of NwkID reach the air.\n' % (t, NWKID_BITS[t]))
            last_type = t
        w('    { 0x%06X, "%s" },%s\n'
          % (netid, op.replace('"', '\\"'), '   // +' if isextra else ''))
    w('};\n\n}\n')
    print('%d rows (%d from the page, %d from the extras file), %d dropped, widths %s'
          % (len(out_rows), len(out_rows) - len(extra), len(extra), dropped,
             dict(sorted(widths.items()))), file=sys.stderr)


if __name__ == '__main__':
    main()
